### ISSUE TITLE
broken target link for images

### ISSUE THREAD

**Issue by dsaucez** [dsaucez/blueprint#5]
target link of images does not correspond to a location on the server

**Comment by nimakris** [comment]
seems that there is an option in m2r for parsing relative links added to the sphinx configuration, which is not set currently (**m2r_parse_relative_links**)

https://github.com/miyakogi/m2r/blob/dev/README.md

**Comment by dsaucez** [comment]
fixed by #6

**Comment by dsaucez** [comment]
@nimakris `m2r_parse_relative_links` could be an option but unfortunately m2r is not used directly in  sphinx as there is a python incompatibility (basically sphinx on the portal runs in python2). So we first generate RST files with m2r then run sphinx.
